---

# ensure that the user you will ssh in as can write to your HASS config directory
# - name: ensure config target dir exists
#   file:
#     path: /opt/test/hass
#     mode: 0777
#     state: directory

# overwrites all existing configuration
- name: install new HASS configuration to remote host
  synchronize:
    src: files/
    dest: "/opt/appdata/hass"
  register: hass_config

# must be a separate task so that the ansible-vault decryption installs this file
# in clear text which is required for HASS to read it
- name: copy over secrets
  copy:
    src: secrets.yaml
    dest: "/opt/appdata/hass/secrets.yaml"

# use hass to check config
- name: check HASS config
  command: "docker exec -ti hass python -m homeassistant --config /config --script check_config"

- name: restart docker if config check went ok
  command: docker restart hass
  when:
    - hass_config.changed