- alias: Turn on the lights when the sun sets
  hide_entity: True
  trigger:
    platform: sun
    event: sunset
    offset: "-00:30:00"
  action:
    service: homeassistant.turn_on
    entity_id: light.living_area