- alias: Turn on Porch light at sunset
  hide_entity: True
  trigger:
    platform: sun
    event: sunset
    offset: "-00:15:00"
  action:
    service: light.turn_on
    entity_id: light.porch
- alias: Turn off Porch light at 11pm
  hide_entity: True
  trigger:
    platform: time
    at: '23:00:00'
  action:
    service: light.turn_off
    entity_id: light.porch
