- alias: 'soldering iron check'
  trigger:
    platform: numeric_state
    entity_id: sensor.energy_8_soldering_iron
    value_template: '{{ states.sensor.energy_8_soldering_iron.attributes.ENERGY.Voltage }}'
    above: 100
    for:
      seconds: 5
  action:
    - service: notify.ktzhassbotnotify
      data:
        message: 'You left the soldering iron on for 25 minutes... Now what?'
    - service: homeassistant.turn_off
      entity_id: switch.ac_solderingiron