- alias: 'Telegram bot that reply pong to ping'
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/ping'
  action:
    - service: notify.plexbotnotify
      data:
        message: 'pong'
- alias: 'Restart Plex Docker container'
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/plex'
  action:
    - service: notify.plexbotnotify
      data:
        message: 'Bad Plex. Naughty Plex. Go to your room. Restarting...'
    - service: shell_command.restart_plex_docker
    - delay:
        seconds: 5
    - service: notify.plexbotnotify
      data:
        message: 'Plex has now restarted. w00t!'