- alias: 'Telegram bot that reply ping to pong'
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/pong'
  action:
    - service: notify.ktzhassbotnotify
      data:
        message: 'ping'