# - alias: 'washer_started'
#   trigger:
#     platform: numeric_state
#     entity_id: sensor.energy_6_washer
#     value_template: '{{ states.sensor.energy_6_washer.attributes.ENERGY.Power }}'
#     above: 3
#     for:
#       minutes: 1
#   action:
#     - service: tts.google_say
#       data_template:
#         entity_id: media_player.lounge
#         message: Washing start detected
#     - service: notify.ktzhassbotnotify
#       data:
#         message: 'Washing start detected.'
# - alias: 'washer_finished'
#   trigger:
#     platform: numeric_state
#     entity_id: sensor.energy_6_washer
#     value_template: '{{ states.sensor.energy_6_washer.attributes.ENERGY.Power }}'
#     below: 2
#     for:
#       minutes: 5
#   action:
#     - service: notify.ktzhassbotnotify
#       data:
#         message: 'Washing is finished!'
#     - service: tts.google_say
#       data_template:
#         entity_id: media_player.lounge
#         message: Washing is done
#     - service: light.turn_on
#       data:
#         entity_id: group.LEDs
#         brightness: 200
#         transition: 5