---
version: "2"
services:
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: le
    volumes:
      - /opt/appdata/letsencrypt/config:/config
    ports:
      - 80:80
      - 443:443
    environment:
      - PUID=1000
      - PGID=1000
      - EMAIL=alexktz@gmail.com
      - URL=google.com
      - SUBDOMAINS=subdomain
      - ONLY_SUBDOMAINS=true
      - DHLEVEL=4096
      - TZ=America/New_York
      - VALIDATION=http
    depends_on:
      - hass
    mem_limit: 256m
    restart: always
  hass:
    image: homeassistant/home-assistant
    container_name: hass
    network_mode: host
    volumes:
      - /opt/appdata/hass:/config
    environment:
      - TZ=America/New_York
    restart: unless-stopped
