homeassistant:
  name: !secret hass_name
  latitude: !secret hass_lat
  longitude: !secret hass_long
  elevation: !secret hass_elevation
  unit_system: imperial
  time_zone: America/New_York
  # Customization file
  #customize: !include customize.yaml
tts:
  - platform: google
mqtt:
  password: !secret mqtt_password

frontend:
# lovelace:
#   mode: yaml
config: 
updater:
#discovery:
conversation:
history:
logbook:
map:
sun:
system_health:
hue:
  bridges:
    - host: 192.168.1.210

#group: !include groups.yaml
light: !include_dir_merge_list lights/
automation: !include_dir_merge_list automations/
switch: !include_dir_merge_list switches/
sensor: !include_dir_merge_list sensor/

script: !include_dir_merge_named scripts/
google_assistant: !include_dir_merge_named google-assistant/
nest: !include_dir_merge_named nest/
ifttt: !include_dir_merge_named ifttt/
telegram_bot: !include_dir_merge_list telegram/
notify: !include_dir_merge_list notify/
shell_command: !include_dir_merge_named shell/
influxdb: !include_dir_merge_named influxdb/
