darkness:
  alias: darkness
  sequence:
    - service: light.turn_off
      data:
        entity_id: group.all_lights
        transition: 5
    - service: tts.google_say
      data_template:
        entity_id: media_player.lounge
        message: The midnight hour must be close at hand.