imhome:
  alias: im home
  sequence:
    - service: light.turn_on
      data:
        entity_id: light.living_area
        transition: 10
        brightness: 255
    - service: tts.google_say
      data_template:
        entity_id: media_player.lounge
        message: Welcome home sir.
    - service: nest.set_away_mode
      data:
        away_mode: home