morning:
  alias: good morning
  sequence:
    - service: tts.google_say
      data_template:
        entity_id: media_player.lounge
        message: Morning routine initiated! Good morning Kretzschmars!!!
    - service: tts.google_say
      data_template:
        entity_id: media_player.bedroom
        message: Morning routine initiated! Good morning Kretzschmars!!!
    - service: tts.google_say
      data_template:
        entity_id: media_player.kitchen
        message: Morning routine initiated! Good morning Kretzschmars!!!
    - service: light.turn_on
      data:
        entity_id: group.all_lights
        transition: 30
        brightness: 255