movietime:
  alias: movie time
  sequence:
    - service: light.turn_off
      data:
        entity_id: group.all_lights
        transition: 10
    - service: light.turn_on
      data:
        entity_id: light.living_area
        transition: 30
        brightness: 180