- platform: mqtt
  schema: json
  effect: true
  effect_list:
    - bpm
    - confetti
    - cyclon rainbow
    - dots
    - fire
    - glitter
    - juggle
    - lightning
    - noise
    - police all
    - police one
    - rainbow
    - sinelon
    - solid
  brightness: true
  rgb: true
  optimistic: false
  qos: 0
  name: "Chimney"
  state_topic: "leds/lounge/chimney"
  command_topic: "leds/lounge/chimney/set"